# Generated by Django 4.2.1 on 2023-06-16 09:45

from django.db import migrations, models
import temp_project.web.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firs_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('age', models.PositiveIntegerField(max_length=35)),
                ('egn', models.CharField(max_length=10, validators=[temp_project.web.validators.egn_validator])),
            ],
        ),
    ]
