# Generated by Django 4.2.1 on 2023-06-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tools', '0002_remove_employees_id_employees_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='first_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='last_name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
