# Generated by Django 4.2.1 on 2023-06-13 11:55

from django.db import migrations, models
import temp_project.user_and_pass.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user_and_pass', '0002_appuser_groups_appuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='appuser',
            managers=[
                ('objects', temp_project.user_and_pass.managers.AppUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
