# Generated by Django 4.2.1 on 2023-06-14 10:17

import django.core.validators
from django.db import migrations, models
import petstagram.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram.accounts.validators.validate_only_letter]),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(2), petstagram.accounts.validators.validate_only_letter]),
        ),
    ]
